/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { MatchResults } from "@stencil/router";
export namespace Components {
    interface AppHome {
    }
    interface AppProfile {
        "match": MatchResults;
    }
    interface AppRoot {
        "pageTitle": string;
    }
    interface OrgList {
    }
    interface ResourcesFinancial {
        /**
          * 4. Public Property API Inlined decorator, alphabetical order. These are different than "own properties" in that public props are exposed as properties and attributes on the host element. Requires JSDocs for public API documentation.
         */
        "match": MatchResults;
        "showMore": boolean;
    }
    interface SeeMore {
        "show": boolean;
    }
    interface SlidePanel {
    }
}
declare global {
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {
    }
    var HTMLAppProfileElement: {
        prototype: HTMLAppProfileElement;
        new (): HTMLAppProfileElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLOrgListElement extends Components.OrgList, HTMLStencilElement {
    }
    var HTMLOrgListElement: {
        prototype: HTMLOrgListElement;
        new (): HTMLOrgListElement;
    };
    interface HTMLResourcesFinancialElement extends Components.ResourcesFinancial, HTMLStencilElement {
    }
    var HTMLResourcesFinancialElement: {
        prototype: HTMLResourcesFinancialElement;
        new (): HTMLResourcesFinancialElement;
    };
    interface HTMLSeeMoreElement extends Components.SeeMore, HTMLStencilElement {
    }
    var HTMLSeeMoreElement: {
        prototype: HTMLSeeMoreElement;
        new (): HTMLSeeMoreElement;
    };
    interface HTMLSlidePanelElement extends Components.SlidePanel, HTMLStencilElement {
    }
    var HTMLSlidePanelElement: {
        prototype: HTMLSlidePanelElement;
        new (): HTMLSlidePanelElement;
    };
    interface HTMLElementTagNameMap {
        "app-home": HTMLAppHomeElement;
        "app-profile": HTMLAppProfileElement;
        "app-root": HTMLAppRootElement;
        "org-list": HTMLOrgListElement;
        "resources-financial": HTMLResourcesFinancialElement;
        "see-more": HTMLSeeMoreElement;
        "slide-panel": HTMLSlidePanelElement;
    }
}
declare namespace LocalJSX {
    interface AppHome {
    }
    interface AppProfile {
        "match"?: MatchResults;
    }
    interface AppRoot {
        "pageTitle"?: string;
    }
    interface OrgList {
    }
    interface ResourcesFinancial {
        /**
          * 4. Public Property API Inlined decorator, alphabetical order. These are different than "own properties" in that public props are exposed as properties and attributes on the host element. Requires JSDocs for public API documentation.
         */
        "match"?: MatchResults;
        /**
          * 5. Events section Inlined decorator, alphabetical order. Requires JSDocs for public API documentation.
         */
        "onUpdateTitle"?: (event: CustomEvent<MatchResults>) => void;
        "showMore"?: boolean;
    }
    interface SeeMore {
        "onSeeMore"?: (event: CustomEvent<boolean>) => void;
        "show"?: boolean;
    }
    interface SlidePanel {
    }
    interface IntrinsicElements {
        "app-home": AppHome;
        "app-profile": AppProfile;
        "app-root": AppRoot;
        "org-list": OrgList;
        "resources-financial": ResourcesFinancial;
        "see-more": SeeMore;
        "slide-panel": SlidePanel;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-profile": LocalJSX.AppProfile & JSXBase.HTMLAttributes<HTMLAppProfileElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "org-list": LocalJSX.OrgList & JSXBase.HTMLAttributes<HTMLOrgListElement>;
            "resources-financial": LocalJSX.ResourcesFinancial & JSXBase.HTMLAttributes<HTMLResourcesFinancialElement>;
            "see-more": LocalJSX.SeeMore & JSXBase.HTMLAttributes<HTMLSeeMoreElement>;
            "slide-panel": LocalJSX.SlidePanel & JSXBase.HTMLAttributes<HTMLSlidePanelElement>;
        }
    }
}
